// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: first

#include "ui.h"

void myscreencb(lv_event_t * e)
{
	// Your code here
}
